
    <h1>Úvod</h1>
    <div class="mainContainer">
        <div class="timetable">
            <h2>Rozvrh</h2>
            <h3>Týden 9. až 13.12.2025</h3>
            <table>
                <tr>
                    <th></th>
                    <th>0. hodina</th>
                    <th>1. hodina</th>
                    <th>2. hodina</th>
                    <th>3. hodina</th>
                    <th>4. hodina</th>
                    <th>5. hodina</th>
                    <th>6. hodina</th>
                    <th>7. hodina</th>
                    <th>8. hodina</th>
                    <th>9. hodina</th>
                    <th>10. hodina</th>
                    <th>11. hodina</th>
                    <th>12. hodina</th>
                </tr>
                <tr>
                    <th>Pondělí</th>
                    <td class="cv" colspan="2"><b>US</b><br>Vojáčková <a href="https://nav.vspj.cz">V7</a></td>
                    <td class="pred" colspan="2"><b>DS1</b><br>Bureš <a href="https://nav.vspj.cz">Výukové centrum</a></td>
                    <td class="cv" colspan="2"><b>DS1</b><br>Musil <a href="https://nav.vspj.cz">V9</a></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Úterý</th>
                    <td></td>
                    <td class="cv" colspan="2"><b>AJAI_1</b><br>Dostálová <a href="https://nav.vspj.cz">J1</a></td>
                    <td class="pred test" colspan="2"><b>DS</b><br>Kuklišová Pavelková <a href="https://nav.vspj.cz">Výukové centrum</a><br><b class="important">Povinná účast - Zápočtový test</b></td>
                    <td class="cv" colspan="2"><b>PG1</b><br>Musil <a href="https://nav.vspj.cz">V7</a></td>
                    <td class="pred" colspan="2"><b>PG1</b><br>Richta <a href="https://nav.vspj.cz">P3</a></td>
                    <td class="cv" colspan="2"><b>PS1</b><br>Fraj <a href="https://nav.vspj.cz">EIT</a></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Středa</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="cv" colspan="3"><b>MAT0</b><br>Dvořáková <a href="https://nav.vspj.cz">U13</a></td>
                    <td></td>
                    <td class="cv zruseno" colspan="2"><b>DS</b><br>Kuklišová Pavelková <a href="https://nav.vspj.cz">U15</a><b class="important">Zrušeno</b></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Čtvrtek</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Pátek</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
            <br>
            <h3>Absence učitelů</h3>
            <b>Kuklišová Pavelková:</b>
            <p>11.12. 2025</p>
        </div>
        <div class="messages">
            <h1>
                Nejnovější vzkazy v IS</h1>
            <div class="message-wrap">
                <img src="images/def.png" class="profile-photo" alt="default-user">
                <p class="name">Bc. Martin Fraj</p>
                <p class="date">15.12.2025</p>
                <p class="text">Dobrý den,
                    z časových důvodů bude dnes možné napsat v rámci cvičení pouze teoretický test. Praktickou část zkoušky v případě volné kapacity učebny bude možné udělat zítra od 15:45 hod, případně na řádném termínu, který bude vypsaný a bude v lednu.
                    Děkuji za pochopení.</p>
            </div>
            <p>Zobrazit </p><a href="#">všechny Vzkazy</a>
        </div>
        <div class="credits">
            <h2>Přehled zapsaných předmětů</h2>
            <h3>Aktuální semestr: 1 (Zimní 2025/26)</h3>
            <table>
                <tr>
                    <th>Název předmětu</th>
                    <th>Zapsaný/í vyučující</th>
                    <th>Zkratka v rozvrhu</th>
                    <th colspan="2">Zapsané časy v rozvrhu (cvičení, přednáška)</th>
                    <th>Kredity</th>
                    <th>Započteno?</th>
                    <th>Zakončeno zkouškou?</th>
                    <th>Vypsané termíny</th>
                    <th>Hodnocení</th>
                    <th>Odkaz na Moodle</th>
                </tr>
                <tr>
                    <th>Uživatelský software</th><td>Mgr. Hana Vojáčková, Ph.D.</td><td>US</td><td class="cv"><b>Pondělí 7:10 - 8:45</b> <a href="https://nav.vspj.cz">V7</a></td><td class="pred">Předmět nemá vypsané přednášky</td><td>2</td><td>Ne</td><td>Ne</td><td></td><td></td><td><a href="https://moodle.vspj.cz/course/view.php?id=203951">Moodle</a></td>
                </tr>
                <tr>
                    <th>Úvod do databázových systémů</th><td>doc. Ing. Zbyněk Bureš, Ph.D., Ing. Marek Musil</td><td>DS1</td><td class="cv"><b>Pondělí 10:35 - 12:15</b> <a href="https://nav.vspj.cz">V9</a></td><td class="pred"><b>Pondělí 8:50 - 9:30</b> <a href="https://nav.vspj.cz">Výukové centrum</a></td><td>4</td><td>Ne</td><td>Ne</td><td><a href="terminy/ds1">Termíny</a></td><td></td><td><a href="https://moodle.vspj.cz/course/view.php?id=204074">Moodle</a></td>
                </tr>
                <tr>
                    <th>Základy strukturovaného programování</th><td>doc. Ing. Karel Richta, CSc., Ing. Marek Musil</td><td>PG1</td><td class="cv"><b>Úterý 11:30 - 13:20</b> <a href="https://nav.vspj.cz">V7</a></td><td class="pred"><b>Úterý 13:30 - 15:05</b> <a href="https://nav.vspj.cz">P3</a></td><td>5</td><td>Ano</td><td>Ano</td><td><a href="terminy/pg1">Termíny</a></td><td></td><td></td><td><a href="https://moodle.vspj.cz/course/view.php?id=204038">Moodle</a></td>
                </tr>
                <tr>
                    <th>Úvod do počítačových sítí</th><td>Bc. Martin Fraj, Mgr. Antonín Přibyl</td><td>US</td><td class="cv"><b>Úterý 15:15 - 16:50</b><a href="https://nav.vspj.cz">EIT</a></td><td class="pred"><b>Středa 8:50 - 9:30</b> <a href="https://nav.vspj.cz">P4</a></td><td>5</td><td>Ano</td><td>Ano</td><td></td><td>D</td><td><a href="https://moodle.vspj.cz/course/view.php?id=203951">Moodle</a></td>
                </tr>
                <tr>
                    <th>Diskrétní struktury</th><td>Ing. Lenka Kuklišová Pavelková, Ph.D.</td><td>DS</td><td class="cv"><b>Středa 15:15 - 16:50</b><a href="https://nav.vspj.cz">U15</a></td><td class="pred"><b>Úterý 9:45 - 11:20</b> <a href="https://nav.vspj.cz">Výukové centrum</a></td><td>5</td><td>Ano</td><td>Ano</td><td><a href="terminy/ds">Termíny</a></td><td></td><td><a href="https://moodle.vspj.cz/course/view.php?id=203951">Moodle</a></td>
                </tr>
                <tr>
                    <th>Matematika 0</th><td>Ing. Stanislava Dvořáková, Ph.D.</td><td>MAT0</td><td class="cv"><b>Středa 11:13 - 14:15</b><a href="https://nav.vspj.cz">U13</a></td><td class="pred">Předmět nemá vypsané přednášky</td><td>2</td><td>Ne</td><td>Ne</td><td></td><td><td></td><a href="https://moodle.vspj.cz/course/view.php?id=203951">Moodle</a></td>
                </tr>
                <tr>
                    <th>Anglický jazyk pro APIN1</th><td>Mgr. Zdeňka Dostálová</td><td>AJAI_1</td><td class="cv"><b>Úterý 8:00 - 9:35</b> <a href="https://nav.vspj.cz">J1</a></td><td class="pred">Předmět nemá vypsané přednášky</td><td>2</td><td>Ano</td><td>Ne</td><td></td><td></td><td><a href="https://moodle.vspj.cz/course/view.php?id=204038">Moodle</a></td>
                </tr>
            </table>
            <h4 class="important">Celkový získaný počet kreditů: <b>7</b></h4>
            <h4 class="important">Počet kreditů pro postup do vyššího semestru: <b>15</b></h4>

        </div>
        <div class="opportunities">
            <h2>Aktuální pracovní příležitosti</h2>
        </div>
    </div>