
    <h1>Úvod</h1>
    <div class="container">
        <div class="timetable">
            <h2>Rozvrh</h2>
            <h3>Týden 9. až 13.12.2025</h3>
            <table>
                <tr>
                    <th></th>
                    <th>0. hodina</th>
                    <th>1. hodina</th>
                    <th>2. hodina</th>
                    <th>3. hodina</th>
                    <th>4. hodina</th>
                    <th>5. hodina</th>
                    <th>6. hodina</th>
                    <th>7. hodina</th>
                    <th>8. hodina</th>
                    <th>9. hodina</th>
                    <th>10. hodina</th>
                    <th>11. hodina</th>
                    <th>12. hodina</th>
                </tr>
                <tr>
                    <th>Pondělí</th>
                    <td class="cv" colspan="2"><b>US</b><br>Vojáčková <a href="https://nav.vspj.cz">V7</a></td>
                    <td class="pred" colspan="2"><b>DS1</b><br>Bureš <a href="https://nav.vspj.cz">Výukové centrum</a></td>
                    <td class="cv" colspan="2"><b>DS1</b><br>Musil <a href="https://nav.vspj.cz">V9</a></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Úterý</th>
                    <td></td>
                    <td class="cv" colspan="2"><b>US</b><br>Dostálová <a href="https://nav.vspj.cz">J1</a></td>
                    <td class="pred zruseno" colspan="2"><b>DS</b><br>Kuklišová Pavelková <a href="https://nav.vspj.cz">Výukové centrum</a><br><b class="important">Zrušeno</b></td>
                    <td class="cv" colspan="2"><b>PG1</b><br>Musil <a href="https://nav.vspj.cz">V7</a></td>
                    <td class="pred" colspan="2"><b>PG1</b><br>Richta <a href="https://nav.vspj.cz">P3</a></td>
                    <td class="cv" colspan="2"><b>PS1</b><br>Fraj <a href="https://nav.vspj.cz">EIT</a></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Středa</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="cv" colspan="3"><b>MAT0</b><br>Dvořáková <a href="https://nav.vspj.cz">U13</a></td>
                    <td></td>
                    <td class="cv" colspan="2"><b>DS</b><br>Kuklišová Pavelková <a href="https://nav.vspj.cz">U15</a></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Čtvrtek</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>Pátek</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
            <br>
            <h3>Absence učitelů</h3>
            <b>Kuklišová Pavelková:</b>
            <p>10.12</p>
        </div>
        <div class="messages">
            <h1>
                Nejnovější vzkazy v IS</h1>
            <div class="message-wrap">
                <img src="images/def.png" class="profile-photo" alt="default-user">
                <p class="name">Bc. Martin Fraj</p>
                <p class="date">15.12.2025</p>
                <p class="text">Dobrý den,
                    z časových důvodů bude dnes možné napsat v rámci cvičení pouze teoretický test. Praktickou část zkoušky v případě volné kapacity učebny bude možné udělat zítra od 15:45 hod, případně na řádném termínu, který bude vypsaný a bude v lednu.
                    Děkuji za pochopení.</p>
            </div>
            <p>Zobrazit </p><a href="#">všechny Vzkazy</a>
        </div>
        <div class="credits">
            <h2>Přehled zapsaných předmětů</h2>
            <table>
                <tr>
                    <th>Název předmětu</th>
                    <th>Zapsaný/í vyučující</th>
                    <th>Zkratka v rozvrhu</th>
                    <th colspan="2">Zapsané časy v rozvrhu (cvičení, přednáška)</th>
                    <th>Kredity</th>
                    <th>Započteno?</th>
                    <th>Zakončeno zkouškou?</th>
                    <th>Vypsané termíny</th>
                    <th>Hodnocení</th>
                    <th>Odkaz na Moodle</th>
                </tr>
                <tr>
                    <th>Uživatelský software</th><td>Mgr. Hana Vojáčková, Ph.D</td><td>US</td><td class="cv"><b>Pondělí 7:10 - 8:45</b><a href="https://nav.vspj.cz">V7</a></td><td class="pred">Předmět nemá vypsané přednášky</td><td>2</td><td>Ne</td><td>Ne</td><td></td><td><a href="https://moodle.vspj.cz/course/view.php?id=203951">Moodle</a></td>
                </tr>
                <tr>
                    <th>Úvod do databázových systémů</th><td>doc. Ing. Zbyněk Bureš, Ph.D., Ing. Marek Musil</td><td>DS1</td><td class="cv"><b>Pondělí 10:35 - 12:15</b><a href="https://nav.vspj.cz">V9</a></td><td class="pred"><b>Pondělí 8:50 - 9:30</b><a href="https://nav.vspj.cz">Výukové centrum</a></td><td>4</td><td>Ne</td><td>Ne</td><td></td><td><a href="https://moodle.vspj.cz/course/view.php?id=204074">Moodle</a></td>
                </tr>
                <tr>
                    <th>Základy strukturovaného programování</th>
                </tr>
                <tr>
                    <th>Úvod do počítačových sítí</th>
                </tr>
                <tr>
                    <th>Diskrétní struktury</th>
                </tr>
                <tr>
                    <th>Matematika 0</th>
                </tr>
                <tr>
                    <th>Anglický jazyk pro APIN</th>
                </tr>
            </table>
        </div>
        <div class="opportunities">
            <h2>Aktuální pracovní příležitosti</h2>
        </div>
    </div>